import type { NextPage } from 'next'
import Head from 'next/head'
import NavBar from '../components/Header/NavBar'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Jevolii</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>

      </main>
    </>
  )
}

export default Home
